### ISSUE TITLE
Use Declarative Services instead of Extensions

### ISSUE THREAD

**Issue by hstaudacher** [sschmidt/webdeployer#1]
When it comes to use the Servlet implementation we should avoid using the extension registry because it's not contained in the RT Packages of the RTP project. Instead we should use Declarative Services to inject the HTTPService dynamically and register the servlet.

The DS bundles will be started automatically in the RT packages and can be used out of the box.

**Comment by sschmidt** [comment]
Currently, the Activator is used to get the required P2 services (i. e. IProvisioningAgent and IProfileRegistry). Perhaps it's also possible to interact with those services using the component.xml and get rid of the Activator. If this thought is reasonable, we'd reopen the issue and improve this.

**Comment by hstaudacher** [comment]
Please see my TODO comments of commit 3cdf3fb59f403fa31c5976a57cc4dc48d76cd0e3

**Comment by sschmidt** [comment]
Thank you for this pointer. DS are really awesome! :-)
