### ISSUE TITLE
P2 Profiles

### ISSUE THREAD

**Issue by sschmidt** [sschmidt/webdeployer#3]
While trying to install a new bundle with the help of the HTTP interface I get an error saying that the profile is null (which is actually true).

In which way should we utilize P2 profiles (i. e. use one profile for each new bundle, use one default profile for each package deployed via http, give the user the ability to manage profiles and choose which profiles is eligible)?

**Comment by hstaudacher** [comment]
hmm, this is a good question. I think for a first shot we should create a default profile. This profile should be used for all install requests via http. 

In a second shot we can make this configurable if requested.
